
## BRISANJE SISPLETA
## PRED BRISANJEM IZVEDI NUJNO BACKUP BAZE!!!


## Najprej testno samo renamamo tabele
ALTER TABLE DeadLinks RENAME TO delete_DeadLinks;
ALTER TABLE PdfIndex RENAME TO delete_PdfIndex;
ALTER TABLE UlCounter RENAME TO delete_UlCounter;
ALTER TABLE acc_companies RENAME TO delete_acc_companies;
ALTER TABLE acc_country RENAME TO delete_acc_country;
ALTER TABLE acc_db RENAME TO delete_acc_db;
ALTER TABLE acc_vir RENAME TO delete_acc_vir;
ALTER TABLE anketa RENAME TO delete_anketa;
ALTER TABLE anketa_opcije RENAME TO delete_anketa_opcije;
ALTER TABLE ankete RENAME TO delete_ankete;
ALTER TABLE base_formula RENAME TO delete_base_formula;
ALTER TABLE baza_clan RENAME TO delete_baza_clan;
ALTER TABLE baza_res2_clan RENAME TO delete_baza_res2_clan;
ALTER TABLE baza_res2_manager RENAME TO delete_baza_res2_manager;
ALTER TABLE baza_res_clan RENAME TO delete_baza_res_clan;
ALTER TABLE baza_res_manager RENAME TO delete_baza_res_manager;
ALTER TABLE chart RENAME TO delete_chart;
ALTER TABLE clan_avtor RENAME TO delete_clan_avtor;
ALTER TABLE clan_baza RENAME TO delete_clan_baza;
ALTER TABLE clan_companies RENAME TO delete_clan_companies;
ALTER TABLE clan_country RENAME TO delete_clan_country;
ALTER TABLE clan_db RENAME TO delete_clan_db;
ALTER TABLE clan_vir RENAME TO delete_clan_vir;
ALTER TABLE comment RENAME TO delete_comment;
ALTER TABLE correlations RENAME TO delete_correlations;
ALTER TABLE costs RENAME TO delete_costs;
ALTER TABLE data_alert_avtor RENAME TO delete_data_alert_avtor;
ALTER TABLE data_alert_mail RENAME TO delete_data_alert_mail;
ALTER TABLE data_alert_when RENAME TO delete_data_alert_when;
ALTER TABLE data_avtor RENAME TO delete_data_avtor;
ALTER TABLE data_clan RENAME TO delete_data_clan;
ALTER TABLE data_companies RENAME TO delete_data_companies;
ALTER TABLE data_companies_avtor RENAME TO delete_data_companies_avtor;
ALTER TABLE data_country_avtor RENAME TO delete_data_country_avtor;
ALTER TABLE data_db RENAME TO delete_data_db;
ALTER TABLE data_db_avtor RENAME TO delete_data_db_avtor;
ALTER TABLE data_manager RENAME TO delete_data_manager;
ALTER TABLE data_vir RENAME TO delete_data_vir;
ALTER TABLE data_vir_avtor RENAME TO delete_data_vir_avtor;
ALTER TABLE db_viewcount RENAME TO delete_db_viewcount;
ALTER TABLE events RENAME TO delete_events;
ALTER TABLE faq RENAME TO delete_faq;
ALTER TABLE favorites RENAME TO delete_favorites;
ALTER TABLE finance_stats RENAME TO delete_finance_stats;
ALTER TABLE formula RENAME TO delete_formula;
ALTER TABLE forum_menu RENAME TO delete_forum_menu;
ALTER TABLE grid RENAME TO delete_grid;
ALTER TABLE hour_arhiv RENAME TO delete_hour_arhiv;
ALTER TABLE hour_comment RENAME TO delete_hour_comment;
ALTER TABLE hour_comment_project RENAME TO delete_hour_comment_project;
ALTER TABLE hour_comment_user RENAME TO delete_hour_comment_user;
ALTER TABLE hour_delovneure RENAME TO delete_hour_delovneure;
ALTER TABLE hour_dogodek_project RENAME TO delete_hour_dogodek_project;
ALTER TABLE hour_middle_user RENAME TO delete_hour_middle_user;
ALTER TABLE hour_name RENAME TO delete_hour_name;
ALTER TABLE hour_paid RENAME TO delete_hour_paid;
ALTER TABLE hour_planned RENAME TO delete_hour_planned;
ALTER TABLE hour_skupina RENAME TO delete_hour_skupina;
ALTER TABLE hour_user_dopust RENAME TO delete_hour_user_dopust;
ALTER TABLE hour_work RENAME TO delete_hour_work;
ALTER TABLE hour_working_days RENAME TO delete_hour_working_days;
ALTER TABLE hour_zaposlitev RENAME TO delete_hour_zaposlitev;
ALTER TABLE ip_allow RENAME TO delete_ip_allow;
ALTER TABLE kat_avtor RENAME TO delete_kat_avtor;
ALTER TABLE kat_companies RENAME TO delete_kat_companies;
ALTER TABLE kat_country RENAME TO delete_kat_country;
ALTER TABLE kat_keywords RENAME TO delete_kat_keywords;
ALTER TABLE kat_vir RENAME TO delete_kat_vir;
ALTER TABLE manager_avtor RENAME TO delete_manager_avtor;
ALTER TABLE manager_baza RENAME TO delete_manager_baza;
ALTER TABLE manager_companies RENAME TO delete_manager_companies;
ALTER TABLE manager_country RENAME TO delete_manager_country;
ALTER TABLE manager_db RENAME TO delete_manager_db;
ALTER TABLE manager_vir RENAME TO delete_manager_vir;
ALTER TABLE rss RENAME TO delete_rss;
ALTER TABLE rubrika1 RENAME TO delete_rubrika1;
ALTER TABLE rubrika3 RENAME TO delete_rubrika3;
ALTER TABLE sidelist RENAME TO delete_sidelist;
ALTER TABLE srv_branch RENAME TO delete_srv_branch;
ALTER TABLE srv_call_comment RENAME TO delete_srv_call_comment;
ALTER TABLE srv_survey_skins RENAME TO delete_srv_survey_skins;
ALTER TABLE srv_survey_skins_groups RENAME TO delete_srv_survey_skins_groups;
ALTER TABLE struktura_companies RENAME TO delete_struktura_companies;
ALTER TABLE struktura_dd RENAME TO delete_struktura_dd;
ALTER TABLE super_r RENAME TO delete_super_r;

## OSTALE TABELE VEZANE NA SISPLET
ALTER TABLE acc_avtor RENAME TO delete_acc_avtor;
ALTER TABLE aktualno RENAME TO delete_aktualno;
ALTER TABLE baza_help RENAME TO delete_baza_help;
ALTER TABLE baza_insert_clani RENAME TO delete_baza_insert_clani;
ALTER TABLE baza_manager RENAME TO delete_baza_manager;
ALTER TABLE baza_menu RENAME TO delete_baza_menu;
ALTER TABLE clan_forum RENAME TO delete_clan_forum;
ALTER TABLE conferences RENAME TO delete_conferences;
ALTER TABLE content RENAME TO delete_content;
ALTER TABLE data_baze RENAME TO delete_data_baze;
ALTER TABLE data_country RENAME TO delete_data_country;
ALTER TABLE data_dds RENAME TO delete_data_dds;
ALTER TABLE data_kategorij RENAME TO delete_data_kategorij;
ALTER TABLE db_index RENAME TO delete_db_index;
ALTER TABLE direct_access RENAME TO delete_direct_access;
ALTER TABLE display RENAME TO delete_display;
ALTER TABLE extra_row RENAME TO delete_extra_row;
ALTER TABLE extra_row_txt RENAME TO delete_extra_row_txt;
ALTER TABLE finance_flags RENAME TO delete_finance_flags;
ALTER TABLE footer RENAME TO delete_footer;
ALTER TABLE footer_novice RENAME TO delete_footer_novice;
ALTER TABLE forum_group RENAME TO delete_forum_group;
ALTER TABLE forum_index RENAME TO delete_forum_index;
ALTER TABLE forum_track RENAME TO delete_forum_track;
ALTER TABLE groups RENAME TO delete_groups;
ALTER TABLE hour_active RENAME TO delete_hour_active;
ALTER TABLE hour_middle_project RENAME TO delete_hour_middle_project;
ALTER TABLE hour_project RENAME TO delete_hour_project;
ALTER TABLE hour_users RENAME TO delete_hour_users;
ALTER TABLE hour_views RENAME TO delete_hour_views;
ALTER TABLE kategorije_baze RENAME TO delete_kategorije_baze;
ALTER TABLE kat_db RENAME TO delete_kat_db;
ALTER TABLE mailnovice RENAME TO delete_mailnovice;
ALTER TABLE manager_forum RENAME TO delete_manager_forum;
ALTER TABLE meeting RENAME TO delete_meeting;
ALTER TABLE menu RENAME TO delete_menu;
ALTER TABLE msn_users RENAME TO delete_msn_users;
ALTER TABLE new RENAME TO delete_new;
ALTER TABLE neww RENAME TO delete_neww;
ALTER TABLE novice RENAME TO delete_novice;
ALTER TABLE obvescanje_forum RENAME TO delete_obvescanje_forum;
ALTER TABLE obvescanje_tema RENAME TO delete_obvescanje_tema;
ALTER TABLE rc33_misc RENAME TO delete_rc33_misc;
ALTER TABLE rubrika2 RENAME TO delete_rubrika2;
ALTER TABLE rubrika4 RENAME TO delete_rubrika4;
ALTER TABLE r_active_cat RENAME TO delete_r_active_cat;
ALTER TABLE selections RENAME TO delete_selections;
ALTER TABLE sessions RENAME TO delete_sessions;
ALTER TABLE struktura_avtor RENAME TO delete_struktura_avtor;
ALTER TABLE struktura_baze RENAME TO delete_struktura_baze;
ALTER TABLE struktura_country RENAME TO delete_struktura_country;
ALTER TABLE struktura_db RENAME TO delete_struktura_db;
ALTER TABLE struktura_dodatninapisi RENAME TO delete_struktura_dodatninapisi;
ALTER TABLE struktura_grid RENAME TO delete_struktura_grid;
ALTER TABLE struktura_kategorij RENAME TO delete_struktura_kategorij;
ALTER TABLE struktura_vir RENAME TO delete_struktura_vir;
ALTER TABLE sum RENAME TO delete_sum;
ALTER TABLE teaser RENAME TO delete_teaser;
ALTER TABLE title RENAME TO delete_title;
ALTER TABLE tracking RENAME TO delete_tracking;
ALTER TABLE vdori RENAME TO delete_vdori;
ALTER TABLE views_forum RENAME TO delete_views_forum;
ALTER TABLE vodic RENAME TO delete_vodic;





## Ce je vse ok lahko potem pobrisemo tabele
DROP TABLE delete_DeadLinks;
DROP TABLE delete_PdfIndex;
DROP TABLE delete_UlCounter;
DROP TABLE delete_acc_companies;
DROP TABLE delete_acc_country;
DROP TABLE delete_acc_db;
DROP TABLE delete_acc_vir;
DROP TABLE delete_anketa;
DROP TABLE delete_anketa_opcije;
DROP TABLE delete_ankete;
DROP TABLE delete_base_formula;
DROP TABLE delete_baza_clan;
DROP TABLE delete_baza_res2_clan;
DROP TABLE delete_baza_res2_manager;
DROP TABLE delete_baza_res_clan;
DROP TABLE delete_baza_res_manager;
DROP TABLE delete_chart;
DROP TABLE delete_clan_avtor;
DROP TABLE delete_clan_baza;
DROP TABLE delete_clan_companies;
DROP TABLE delete_clan_country;
DROP TABLE delete_clan_db;
DROP TABLE delete_clan_vir;
DROP TABLE delete_comment;
DROP TABLE delete_correlations;
DROP TABLE delete_costs;
DROP TABLE delete_data_alert_avtor;
DROP TABLE delete_data_alert_mail;
DROP TABLE delete_data_alert_when;
DROP TABLE delete_data_avtor;
DROP TABLE delete_data_clan;
DROP TABLE delete_data_companies;
DROP TABLE delete_data_companies_avtor;
DROP TABLE delete_data_country_avtor;
DROP TABLE delete_data_db;
DROP TABLE delete_data_db_avtor;
DROP TABLE delete_data_manager;
DROP TABLE delete_data_vir;
DROP TABLE delete_data_vir_avtor;
DROP TABLE delete_db_viewcount;
DROP TABLE delete_events;
DROP TABLE delete_faq;
DROP TABLE delete_favorites;
DROP TABLE delete_finance_stats;
DROP TABLE delete_formula;
DROP TABLE delete_forum_menu;
DROP TABLE delete_grid;
DROP TABLE delete_hour_arhiv;
DROP TABLE delete_hour_comment;
DROP TABLE delete_hour_comment_project;
DROP TABLE delete_hour_comment_user;
DROP TABLE delete_hour_delovneure;
DROP TABLE delete_hour_dogodek_project;
DROP TABLE delete_hour_middle_user;
DROP TABLE delete_hour_name;
DROP TABLE delete_hour_paid;
DROP TABLE delete_hour_planned;
DROP TABLE delete_hour_skupina;
DROP TABLE delete_hour_user_dopust;
DROP TABLE delete_hour_work;
DROP TABLE delete_hour_working_days;
DROP TABLE delete_hour_zaposlitev;
DROP TABLE delete_ip_allow;
DROP TABLE delete_kat_avtor;
DROP TABLE delete_kat_companies;
DROP TABLE delete_kat_country;
DROP TABLE delete_kat_keywords;
DROP TABLE delete_kat_vir;
DROP TABLE delete_manager_avtor;
DROP TABLE delete_manager_baza;
DROP TABLE delete_manager_companies;
DROP TABLE delete_manager_country;
DROP TABLE delete_manager_db;
DROP TABLE delete_manager_vir;
DROP TABLE delete_rss;
DROP TABLE delete_rubrika1;
DROP TABLE delete_rubrika3;
DROP TABLE delete_sidelist;
DROP TABLE delete_srv_branch;
DROP TABLE delete_srv_call_comment;
DROP TABLE delete_srv_survey_skins;
DROP TABLE delete_srv_survey_skins_groups;
DROP TABLE delete_struktura_companies;
DROP TABLE delete_struktura_dd;
DROP TABLE delete_super_r;

## OSTALE TABELE VEZANE NA SISPLET
DROP TABLE delete_acc_avtor;
DROP TABLE delete_aktualno;
DROP TABLE delete_baza_help;
DROP TABLE delete_baza_insert_clani;
DROP TABLE delete_baza_manager;
DROP TABLE delete_baza_menu;
DROP TABLE delete_clan_forum;
DROP TABLE delete_conferences;
DROP TABLE delete_content;
DROP TABLE delete_data_baze;
DROP TABLE delete_data_country;
DROP TABLE delete_data_dds;
DROP TABLE delete_data_kategorij;
DROP TABLE delete_db_index;
DROP TABLE delete_direct_access;
DROP TABLE delete_display;
DROP TABLE delete_extra_row;
DROP TABLE delete_extra_row_txt;
DROP TABLE delete_finance_flags;
DROP TABLE delete_footer;
DROP TABLE delete_footer_novice;
DROP TABLE delete_forum_group;
DROP TABLE delete_forum_index;
DROP TABLE delete_forum_track;
DROP TABLE delete_groups;
DROP TABLE delete_hour_active;
DROP TABLE delete_hour_middle_project;
DROP TABLE delete_hour_project;
DROP TABLE delete_hour_users;
DROP TABLE delete_hour_views;
DROP TABLE delete_kategorije_baze;
DROP TABLE delete_kat_db;
DROP TABLE delete_mailnovice;
DROP TABLE delete_manager_forum;
DROP TABLE delete_meeting;
DROP TABLE delete_menu;
DROP TABLE delete_msn_users;
DROP TABLE delete_new;
DROP TABLE delete_neww;
DROP TABLE delete_novice;
DROP TABLE delete_obvescanje_forum;
DROP TABLE delete_obvescanje_tema;
DROP TABLE delete_rc33_misc;
DROP TABLE delete_rubrika2;
DROP TABLE delete_rubrika4;
DROP TABLE delete_r_active_cat;
DROP TABLE delete_selections;
DROP TABLE delete_sessions;
DROP TABLE delete_struktura_avtor;
DROP TABLE delete_struktura_baze;
DROP TABLE delete_struktura_country;
DROP TABLE delete_struktura_db;
DROP TABLE delete_struktura_dodatninapisi;
DROP TABLE delete_struktura_grid;
DROP TABLE delete_struktura_kategorij;
DROP TABLE delete_struktura_vir;
DROP TABLE delete_sum;
DROP TABLE delete_teaser;
DROP TABLE delete_title;
DROP TABLE delete_tracking;
DROP TABLE delete_vdori;
DROP TABLE delete_views_forum;
DROP TABLE delete_vodic;
